// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0au9NL4FLSfMBDwj0D5Ee7TdwN9JXKxA',
    appId: '1:517468367715:web:b8c603c4eddd3bf2830156',
    messagingSenderId: '517468367715',
    projectId: 'ston-3ed5b',
    authDomain: 'ston-3ed5b.firebaseapp.com',
    storageBucket: 'ston-3ed5b.firebasestorage.app',
    measurementId: 'G-PHCQM5EZL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZhkyzw6bkTCeyNf4J5KG_feQypoQzDk',
    appId: '1:517468367715:android:a93fd1ddab113dd3830156',
    messagingSenderId: '517468367715',
    projectId: 'ston-3ed5b',
    storageBucket: 'ston-3ed5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8QMncdu4KBIun3pkIwV3_2qMAzWsj9Cw',
    appId: '1:517468367715:ios:b95c6280a4df6c68830156',
    messagingSenderId: '517468367715',
    projectId: 'ston-3ed5b',
    storageBucket: 'ston-3ed5b.firebasestorage.app',
    iosBundleId: 'com.example.koto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8QMncdu4KBIun3pkIwV3_2qMAzWsj9Cw',
    appId: '1:517468367715:ios:b95c6280a4df6c68830156',
    messagingSenderId: '517468367715',
    projectId: 'ston-3ed5b',
    storageBucket: 'ston-3ed5b.firebasestorage.app',
    iosBundleId: 'com.example.koto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0au9NL4FLSfMBDwj0D5Ee7TdwN9JXKxA',
    appId: '1:517468367715:web:1c3cd5da0df19107830156',
    messagingSenderId: '517468367715',
    projectId: 'ston-3ed5b',
    authDomain: 'ston-3ed5b.firebaseapp.com',
    storageBucket: 'ston-3ed5b.firebasestorage.app',
    measurementId: 'G-B5DVYDH7YY',
  );
}
